### ISSUE TITLE
Make realization funcs from context menu

### ISSUE THREAD

**Issue by IlyaM1** [IlyaM1/TestBuilder#30]
Make realization funcs from Custom_Widgets/Item.py:
def see_detail_information:
    (under question, so postpone it)
def edit:
    finds the test/user by id, opens Admin_test_view/Admin_user_view to edit
def delete:
    delete the test/user by id

**Comment by akrisfx** [comment]
какое меню? ссылки на строки, и файлы оставляй

**Comment by akrisfx** [comment]
пока ты это не начнешь делать, мы не сможем вылезти из дискорда @IlyaM1 
ткк и я и ты не будем понимать где и что делать по чужим таскам

**Comment by IlyaM1** [comment]
updated

**Comment by IlyaM1** [comment]
@akrisfx

**Comment by akrisfx** [comment]
https://github.com/IlyaM1/TestBuilder/blob/22ad1ae325d3ac4f0f7af48f7a788106ccdc4b09/Custom_Widgets/Item.py#L11 сюда на вход должен идти целиком юзер/тест, смысл делать еще одно обращение к дб? Поэтому перекидывай на этот виджет целиком объект юзера/теста 
@IlyaM1

**Comment by akrisfx** [comment]
@IlyaM1
